function createfigure(X1, Y1, U1, V1)
%CREATEFIGURE(X1, Y1, U1, V1)
%  X1:  quiver x
%  Y1:  quiver y
%  U1:  quiver u
%  V1:  quiver v

%  Auto-generated by MATLAB on 16-Apr-2021 02:19:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create quiver
quiver(X1,Y1,U1,V1,'ShowArrowHead','off','Marker','.','Color',[0 0 1]);

box(axes1,'on');
hold(axes1,'off');
